In [1]:
import numpy as np
import pandas as pd

DF = pd.read_csv(r"C:\Users\pdawg\OneDrive\CDC 2026 DATA\doi-10.7281-t170wn53\index_scores_v3_2026.csv")

In [ ]:
for i in DF.columns:
    print(f"{i} and {DF[i].isna().sum()}")

NCESSCH and 0
Name and 0
School District and 0
State and 0
FIPS County Code and 0
County and 0
City and 0
Zip Code and 0
SAB Available and 0
Gini index and 0
Economic and 0
Education and 285
Health and 96
Housing and 287
Crime and 3219
Composite Score and 0
Economic Percentile Rank and 0
Education Percentile Rank and 285
Health Percentile Rank and 96
Housing Percentile Rank and 287
Crime Percentile Rank and 3219
Composite Score Percentile Rank and 0
Economic Median and 0
Education Median and 0
Health Median and 0
Housing Median and 0
Crime Median and 0
Composite Score Median and 0
Unemployment and 0
Poverty and 289
Access to broadband internet and 287
Single-parent households and 416
Linguistic isolation and 287
Access to healthcare and 289
Infant mortality rate and 5830
SNAP recipients and 301
Low birth weight and 516
Lead exposure risk and 12296
Housing vacancy rate and 287
Housing affordability and 287
Park access and 12246
Violent crime rate and 5879
Incarceration rate and 5422
Less than HS and 285
2-year college or higher and 285
2-year college and 285
4-year college and 285
Graduate or professional degree and 285
White alone and 285
Black or African American alone and 285
American Indian and Alaska Native alone and 285
Asian alone and 285
Native Hawaiian and Other Pacific Islander alone and 285
Some other race alone and 285
Two or more races and 285
Hispanic or Latino and 285

,NCESSCH,Name,School District,State,FIPS County Code,County,City,Zip Code,SAB Available,Gini index,...,4-year college,Graduate or professional degree,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Hispanic or Latino
sum,6.741649e+15,Albertville High SchoolAsbury High SchoolDougl...,Albertville CityMarshall CountyMarshall County...,ALALALALALALALALALALALALALALALALALALALALALALAL...,672932136,Marshall CountyMarshall CountyMarshall CountyM...,AlbertvilleAlbertvilleDouglasGrantGuntersville...,1288692804,12807,10803.70,...,1464162.0,1946026.0,1591916.0,243709.0,35309.0,88289.0,2258.0,136816.0,229687.0,406608.0
min,1.000050e+10,112 Alc Independent Study,21St Century Cyber Cs,AK,1001,Abbeville County,Abbeville,602,0,0.29,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
listofstates = DF["State"].unique().tolist()
listofstates

dict_of_means = {}
for i in listofstates:
    print(f"{i} Summary : {DF["4-year college"][DF["State"] == i].mean()} ==========================")
    dict_of_means[i] = [DF["4-year college"][DF["State"] == i].mean()]

AL Summary : 72.10344827586206 ==========================
AK Summary : 64.76 ==========================
AZ Summary : 65.28998699609883 ==========================
AR Summary : 73.66246056782335 ==========================
CA Summary : 61.1798821930222 ==========================
CO Summary : 50.785547785547784 ==========================
CT Summary : 51.25 ==========================
DE Summary : 64.17073170731707 ==========================
DC Summary : 55.275 ==========================
MD Summary : 56.68376068376068 ==========================
FL Summary : 62.900432900432904 ==========================
GA Summary : 65.01969365426696 ==========================
HI Summary : 57.13953488372093 ==========================
ID Summary : 65.95408163265306 ==========================
IL Summary : 62.289989680082556 ==========================
IN Summary : 68.34192037470726 ==========================
IA Summary : 63.34513274336283 ==========================
KS Summary : 62.7027027027027 ==========================
KY Summary : 73.75505617977528 ==========================
LA Summary : 71.11567164179104 ==========================
ME Summary : 58.043103448275865 ==========================
MA Summary : 51.016260162601625 ==========================
MI Summary : 64.85699693564862 ==========================
MN Summary : 54.490490490490494 ==========================
MS Summary : 75.33548387096774 ==========================
MO Summary : 67.93383458646616 ==========================
MT Summary : 60.43103448275862 ==========================
NE Summary : 61.28164556962025 ==========================
NV Summary : 70.50675675675676 ==========================
NH Summary : 55.14736842105263 ==========================
NJ Summary : 48.0 ==========================
NM Summary : 71.06481481481481 ==========================
NY Summary : 56.85256950294861 ==========================
NC Summary : 62.35126050420168 ==========================
ND Summary : 61.35028248587571 ==========================
OH Summary : 66.38126361655773 ==========================
OK Summary : 70.39529914529915 ==========================
OR Summary : 62.80377358490566 ==========================
PA Summary : 62.84410112359551 ==========================
RI Summary : 55.04545454545455 ==========================
SC Summary : 65.55172413793103 ==========================
SD Summary : 61.65151515151515 ==========================
TN Summary : 66.67951807228916 ==========================
TX Summary : 65.10153358011634 ==========================
UT Summary : 54.67171717171717 ==========================
VT Summary : 54.5 ==========================
VA Summary : 59.02121212121212 ==========================
WA Summary : 60.15668202764977 ==========================
WV Summary : 76.42727272727272 ==========================
WI Summary : 62.687943262411345 ==========================
WY Summary : 65.4090909090909 ==========================
PR Summary : 60.30731707317073 ==========================

In [46]:
dict_of_means

{'AL': [np.float64(72.10344827586206)],
 'AK': [np.float64(64.76)],
 'AZ': [np.float64(65.28998699609883)],
 'AR': [np.float64(73.66246056782335)],
 'CA': [np.float64(61.1798821930222)],
 'CO': [np.float64(50.785547785547784)],
 'CT': [np.float64(51.25)],
 'DE': [np.float64(64.17073170731707)],
 'DC': [np.float64(55.275)],
 'MD': [np.float64(56.68376068376068)],
 'FL': [np.float64(62.900432900432904)],
 'GA': [np.float64(65.01969365426696)],
 'HI': [np.float64(57.13953488372093)],
 'ID': [np.float64(65.95408163265306)],
 'IL': [np.float64(62.289989680082556)],
 'IN': [np.float64(68.34192037470726)],
 'IA': [np.float64(63.34513274336283)],
 'KS': [np.float64(62.7027027027027)],
 'KY': [np.float64(73.75505617977528)],
 'LA': [np.float64(71.11567164179104)],
 'ME': [np.float64(58.043103448275865)],
 'MA': [np.float64(51.016260162601625)],
 'MI': [np.float64(64.85699693564862)],
 'MN': [np.float64(54.490490490490494)],
 'MS': [np.float64(75.33548387096774)],
 'MO': [np.float64(67.93383458646616)],
 'MT': [np.float64(60.43103448275862)],
 'NE': [np.float64(61.28164556962025)],
 'NV': [np.float64(70.50675675675676)],
 'NH': [np.float64(55.14736842105263)],
 'NJ': [np.float64(48.0)],
 'NM': [np.float64(71.06481481481481)],
 'NY': [np.float64(56.85256950294861)],
 'NC': [np.float64(62.35126050420168)],
 'ND': [np.float64(61.35028248587571)],
 'OH': [np.float64(66.38126361655773)],
 'OK': [np.float64(70.39529914529915)],
 'OR': [np.float64(62.80377358490566)],
 'PA': [np.float64(62.84410112359551)],
 'RI': [np.float64(55.04545454545455)],
 'SC': [np.float64(65.55172413793103)],
 'SD': [np.float64(61.65151515151515)],
 'TN': [np.float64(66.67951807228916)],
 'TX': [np.float64(65.10153358011634)],
 'UT': [np.float64(54.67171717171717)],
 'VT': [np.float64(54.5)],
 'VA': [np.float64(59.02121212121212)],
 'WA': [np.float64(60.15668202764977)],
 'WV': [np.float64(76.42727272727272)],
 'WI': [np.float64(62.687943262411345)],
 'WY': [np.float64(65.4090909090909)],
 'PR': [np.float64(60.30731707317073)]}

In [47]:
DF_Means = pd.DataFrame(dict_of_means)
DF_Means.T.sort_values(0)

            0
NJ  48.000000
CO  50.785548
MA  51.016260
CT  51.250000
MN  54.490490
VT  54.500000
UT  54.671717
RI  55.045455
NH  55.147368
DC  55.275000
MD  56.683761
NY  56.852570
HI  57.139535
ME  58.043103
VA  59.021212
WA  60.156682
PR  60.307317
MT  60.431034
CA  61.179882
NE  61.281646
ND  61.350282
SD  61.651515
IL  62.289990
NC  62.351261
WI  62.687943
KS  62.702703
OR  62.803774
PA  62.844101
FL  62.900433
IA  63.345133
DE  64.170732
AK  64.760000
MI  64.856997
GA  65.019694
TX  65.101534
AZ  65.289987
WY  65.409091
SC  65.551724
ID  65.954082
OH  66.381264
TN  66.679518
MO  67.933835
IN  68.341920
OK  70.395299
NV  70.506757
NM  71.064815
LA  71.115672
AL  72.103448
AR  73.662461
KY  73.755056
MS  75.335484
WV  76.427273

In [48]:
dict_of_means = {}
for i in listofstates:
    print(f"{i} Summary : {DF["2-year college"][DF["State"] == i].mean()} ==========================")
    dict_of_means[i] = [DF["2-year college"][DF["State"] == i].mean()]

AL Summary : 65.02709359605912 ==========================
AK Summary : 66.01333333333334 ==========================
AZ Summary : 65.35110533159948 ==========================
AR Summary : 69.89905362776025 ==========================
CA Summary : 69.39284096057997 ==========================
CO Summary : 66.67832167832168 ==========================
CT Summary : 69.3125 ==========================
DE Summary : 69.36585365853658 ==========================
DC Summary : 85.125 ==========================
MD Summary : 73.58547008547009 ==========================
FL Summary : 62.45887445887446 ==========================
GA Summary : 67.59518599562364 ==========================
HI Summary : 57.55813953488372 ==========================
ID Summary : 62.066326530612244 ==========================
IL Summary : 63.88544891640867 ==========================
IN Summary : 64.13348946135831 ==========================
IA Summary : 50.1858407079646 ==========================
KS Summary : 60.65945945945946 ==========================
KY Summary : 65.94606741573034 ==========================
LA Summary : 73.50373134328358 ==========================
ME Summary : 60.55172413793103 ==========================
MA Summary : 70.07046070460704 ==========================
MI Summary : 62.654749744637385 ==========================
MN Summary : 52.8018018018018 ==========================
MS Summary : 59.60645161290323 ==========================
MO Summary : 68.57142857142857 ==========================
MT Summary : 60.02873563218391 ==========================
NE Summary : 51.55379746835443 ==========================
NV Summary : 69.08783783783784 ==========================
NH Summary : 62.32631578947368 ==========================
NJ Summary : 74.49680170575692 ==========================
NM Summary : 66.79629629629629 ==========================
NY Summary : 65.72620050547599 ==========================
NC Summary : 60.60672268907563 ==========================
ND Summary : 43.58757062146893 ==========================
OH Summary : 64.88779956427015 ==========================
OK Summary : 68.88247863247864 ==========================
OR Summary : 62.38867924528302 ==========================
PA Summary : 64.82303370786516 ==========================
RI Summary : 71.25757575757575 ==========================
SC Summary : 62.744827586206895 ==========================
SD Summary : 50.78787878787879 ==========================
TN Summary : 71.46506024096385 ==========================
TX Summary : 70.83818085668958 ==========================
UT Summary : 61.974747474747474 ==========================
VT Summary : 66.46774193548387 ==========================
VA Summary : 69.04242424242425 ==========================
WA Summary : 60.11059907834101 ==========================
WV Summary : 68.75454545454545 ==========================
WI Summary : 55.57446808510638 ==========================
WY Summary : 53.68181818181818 ==========================
PR Summary : 55.43414634146342 ==========================

In [49]:
DF_Means = pd.DataFrame(dict_of_means)
DF_Means.T.sort_values(0)

            0
ND  43.587571
IA  50.185841
SD  50.787879
NE  51.553797
MN  52.801802
WY  53.681818
PR  55.434146
WI  55.574468
HI  57.558140
MS  59.606452
MT  60.028736
WA  60.110599
ME  60.551724
NC  60.606723
KS  60.659459
UT  61.974747
ID  62.066327
NH  62.326316
OR  62.388679
FL  62.458874
MI  62.654750
SC  62.744828
IL  63.885449
IN  64.133489
PA  64.823034
OH  64.887800
AL  65.027094
AZ  65.351105
NY  65.726201
KY  65.946067
AK  66.013333
VT  66.467742
CO  66.678322
NM  66.796296
GA  67.595186
MO  68.571429
WV  68.754545
OK  68.882479
VA  69.042424
NV  69.087838
CT  69.312500
DE  69.365854
CA  69.392841
AR  69.899054
MA  70.070461
TX  70.838181
RI  71.257576
TN  71.465060
LA  73.503731
MD  73.585470
NJ  74.496802
DC  85.125000

In [52]:
dict_of_means = {}
for i in listofstates:
    print(f"{i} Summary : {DF["Less than HS"][DF["State"] == i].mean()} ==========================")
    dict_of_means[i] = [DF["Less than HS"][DF["State"] == i].mean()]

AL Summary : 22.14039408866995 ==========================
AK Summary : 11.986666666666666 ==========================
AZ Summary : 20.729518855656696 ==========================
AR Summary : 20.895899053627762 ==========================
CA Summary : 28.241504304485726 ==========================
CO Summary : 13.727272727272727 ==========================
CT Summary : 10.758928571428571 ==========================
DE Summary : 16.0 ==========================
DC Summary : 14.975 ==========================
MD Summary : 14.76923076923077 ==========================
FL Summary : 19.774891774891774 ==========================
GA Summary : 20.816192560175054 ==========================
HI Summary : 10.790697674418604 ==========================
ID Summary : 16.836734693877553 ==========================
IL Summary : 15.528379772961816 ==========================
IN Summary : 16.82201405152225 ==========================
IA Summary : 10.525073746312684 ==========================
KS Summary : 13.194594594594594 ==========================
KY Summary : 21.644943820224718 ==========================
LA Summary : 23.96641791044776 ==========================
ME Summary : 9.862068965517242 ==========================
MA Summary : 14.474254742547425 ==========================
MI Summary : 13.945863125638407 ==========================
MN Summary : 10.54954954954955 ==========================
MS Summary : 24.570967741935483 ==========================
MO Summary : 16.13684210526316 ==========================
MT Summary : 10.425287356321839 ==========================
NE Summary : 11.712025316455696 ==========================
NV Summary : 25.64189189189189 ==========================
NH Summary : 9.91578947368421 ==========================
NJ Summary : 14.665245202558635 ==========================
NM Summary : 22.087962962962962 ==========================
NY Summary : 19.813816343723673 ==========================
NC Summary : 18.7109243697479 ==========================
ND Summary : 11.661016949152541 ==========================
OH Summary : 14.594771241830065 ==========================
OK Summary : 19.074786324786324 ==========================
OR Summary : 14.543396226415094 ==========================
PA Summary : 13.540730337078651 ==========================
RI Summary : 18.151515151515152 ==========================
SC Summary : 19.251724137931035 ==========================
SD Summary : 12.722222222222221 ==========================
TN Summary : 19.25542168674699 ==========================
TX Summary : 26.94341618191433 ==========================
UT Summary : 11.777777777777779 ==========================
VT Summary : 9.435483870967742 ==========================
VA Summary : 15.76969696969697 ==========================
WA Summary : 15.261136712749616 ==========================
WV Summary : 20.12727272727273 ==========================
WI Summary : 12.03191489361702 ==========================
WY Summary : 10.5 ==========================
PR Summary : 33.1219512195122 ==========================

In [53]:
DF_Means = pd.DataFrame(dict_of_means)
DF_Means.T.sort_values(0)

            0
VT   9.435484
ME   9.862069
NH   9.915789
MT  10.425287
WY  10.500000
IA  10.525074
MN  10.549550
CT  10.758929
HI  10.790698
ND  11.661017
NE  11.712025
UT  11.777778
AK  11.986667
WI  12.031915
SD  12.722222
KS  13.194595
PA  13.540730
CO  13.727273
MI  13.945863
MA  14.474255
OR  14.543396
OH  14.594771
NJ  14.665245
MD  14.769231
DC  14.975000
WA  15.261137
IL  15.528380
VA  15.769697
DE  16.000000
MO  16.136842
IN  16.822014
ID  16.836735
RI  18.151515
NC  18.710924
OK  19.074786
SC  19.251724
TN  19.255422
FL  19.774892
NY  19.813816
WV  20.127273
AZ  20.729519
GA  20.816193
AR  20.895899
KY  21.644944
NM  22.087963
AL  22.140394
LA  23.966418
MS  24.570968
NV  25.641892
TX  26.943416
CA  28.241504
PR  33.121951

In [ ]:
kendall tau


Economic Burden -
Unemployment, Poverty, Access to broadband 
internet, Single-parent households  

Health Burden - 
Infant mortality rate, SNAP recipients, Low birth 
weight, and Lead exposure risk